### PR TITLE
Return error for unregistered sub-commands.

### LINKED ISSUE #37: Return error for unregistered commands
I moved the credentials file `/tmp/.vip-go-api` to simulate not being logged in, and a failing command returns an exit code of `0`. I think it should exit non-zero, so we can more easily detect failures from other scripts.

``` bash
$ mv /tmp/.vip-go-api /tmp/.vip-go-api.bk 
$ vip api GET /sites/123/somecommand
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by joshbetz**
Fixes #37

### CODE REVIEW

**Comment by joshbetz** [comment]
Something is broken with the `vip cli <site>` command.

File: src/bin/vip.js [hunk 1]
```diff
@@ -197,7 +197,10 @@ utils.getCredentials( ( err, user ) => {
 
 	program.parse( process.argv );
 
-	if ( ! process.argv.slice( 2 ).length ) {
-		program.outputHelp();
+	var cmds = program.commands.map(c => c._name);
```
Comment (nickdaugherty) [inline src/bin/vip.js]: Arrow functions FTW - so simple
